version: '3.8'
services:
  #web:
  #  build: .
  #  ports:
  #    - "8080:80"
  #  depends_on:
  #   - db
  php_vulnerable:
    build: ./php_vulnerable
    container_name: php_vulnerable
    ports:
      - "8080:80"
    volumes:
      - ./php_vulnerable:/var/www/html
    depends_on:
      - db

  php_secure:
    build: ./php_secure
    container_name: php_secure
    ports:
    - "8081:80"
    volumes:
    - ./php_secure:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db_data:
